name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Pilih Environment yang ingin di-deploy:'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-apply-${{ github.event.inputs.target_env }}
  cancel-in-progress: false

env:
  AWS_REGION: ap-southeast-1
  TF_IN_AUTOMATION: "true"
  TF_VAR_app_ingress_cidr_blocks: ${{ vars.APP_INGRESS_CIDR_BLOCKS }}

jobs:
  apply:
    name: Apply (${{ github.event.inputs.target_env }})
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=environments/${{ github.event.inputs.target_env }} init -input=false

      - name: Terraform validate
        run: terraform -chdir=environments/${{ github.event.inputs.target_env }} validate

      - name: Terraform plan
        run: terraform -chdir=environments/${{ github.event.inputs.target_env }} plan -input=false -no-color -out=tfplan

      - name: Terraform apply
        run: terraform -chdir=environments/${{ github.event.inputs.target_env }} apply -input=false -auto-approve tfplan
